### PR TITLE
Add an *en* locale file for translations.

### LINKED ISSUE #89: Add lang folder and en.yml as basis for translations.
The goal is to provide a basis for translations of this module.

### PR DESCRIPTION
**Pull request by bummzack**
Include all the official Omnipay 2.x gateways and CreditCard Brands.
Fixes #89

### CODE REVIEW

**Comment by bummzack** [comment]
Could somebody merge this into the `2.0` branch as well, as soon as this gets merged?

**Comment by markguinn** [comment]
Any idea why that test is failing, @bummzack ?

**Comment by bummzack** [comment]
@markguinn It seems like there's a test that checks the gateway title. I translated "Manual" as "Invoice", so this fails: https://github.com/burnbright/silverstripe-omnipay/blob/master/tests/PaymentModelTest.php#L22

Maybe that test can be rewritten? It's gonna fail for all users that add a custom translation for the "Manual" gateway.

**Comment by bummzack** [comment]
I just updated the test so that the "translation" of the gateway doesn't matter.

I think the whole title generation could be improved though. Currently `Payment::getTitle` is some sort of a hybrid when it comes to localization. It does use localized gateway titles, and it *should* use localized currency but outputs a non-localized date. That's probably another issue though… ideally, the title "pattern" could also be translated?

**Comment by markguinn** [comment]
I agree that Title generation is not ideal. I'm open to any solution you propose especially if it comes with a PR attached and solves the problem ;).

Shall I go ahead and merge this one, though, and that can be a separate unit of work?

**Comment by bummzack** [comment]
Yeah, I'll create a new issue for the title-generation.

**Pull request merged**
